spring:
  application:
    name: MeatEco

springdoc:
  swagger-ui:
    path: /api-test

    groups-order: DESC

    tags-sorter: alpha

    operations-sorter: method

  paths-to-match:
    - /api/**

extern:
  naver:
    client-ID: aqljeMYhEg4rpRhjruiZ
    client-Secret: N0TO69U5t8